### ISSUE TITLE
Psychological Safety Vote Area in ubung-4 disappeared

### ISSUE THREAD

**Issue by joe-the-ark** [joe-the-ark/ark#83]
Hi @LehaoLin – something strange happened after you changed the condition – the entire voting area disappeared (screenshot) for all players in a 5 player game...
<img width="1366" alt="Bildschirmfoto 2020-11-10 um 21 00 56" src="https://user-images.githubusercontent.com/64843796/98727410-28b6c580-2398-11eb-8729-15d3ed808455.png">

_Originally posted by @joe-the-ark in https://github.com/joe-the-ark/ark/issues/82#issuecomment-724935463_

**Comment by joe-the-ark** [comment]
@LehaoLin wrote > From the frontend console, the problem is not from my change in issue #82 – it is from other two js cdn. I think we need @linker03 to fix it.

**Comment by LehaoLin** [comment]
![image](https://user-images.githubusercontent.com/35103106/98806015-7e9c7380-2453-11eb-9353-e541a21741a8.png)

From the console, I think the problem is caused by following CDNs.
`<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/tippy.js@6"></script>`
Do you have any solution to the problem? @linker03 

And from the git lens, I found the package was used by Xaoni.
![image](https://user-images.githubusercontent.com/35103106/98806238-d6d37580-2453-11eb-94f6-fd9b50e74c8d.png)
If you have no idea about it, I think you can get help from him. He may know how to do it.

**Comment by linker03** [comment]
Traceback (most recent call last):
  File "/home/soty/Документы/Pythonista/ark_venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/soty/Документы/Pythonista/ark_venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/soty/Документы/Pythonista/ark_venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/soty/Документы/Pythonista/ark/backend/arkserver/decorators.py", line 44, in view
    print('user-valid', user.valid)
AttributeError: 'NoneType' object has no attribute 'valid'
I have this message in terminal when I start the game. 

![image](https://user-images.githubusercontent.com/26412480/98810332-47c16000-2449-11eb-925f-ce7f6b9b8f93.png)
I changed the script source. No more message about tippy and popper

**Comment by LehaoLin** [comment]
You need to launch a game or join a game before enter the game step.

**Comment by LehaoLin** [comment]
I just found the bug and solved it, which was caused by conflicts between vue and other js files.

**Comment by LehaoLin** [comment]
Please have a check, Joe. @joe-the-ark

**Comment by joe-the-ark** [comment]
All good @linker03 & @LehaoLin --- the voting area is back. Thank you for the solution!
